name: GelivyAI Server Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Kodu DUZGUN qovluga cek
        uses: actions/checkout@v4
        with:
          path: /home/suleyman/my_server_project

      - name: Kitabxanalari yenile
        run: |
          cd /home/suleyman/my_server_project
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Butun acarlari tek bir .env faylina yaz
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" > /home/suleyman/my_server_project/.env
          echo "DB=${{ secrets.DB}}" >> /home/suleyman/my_server_project/.env
          echo "GONDEREN_EMAIL=${{ secrets.GONDEREN_EMAIL }}" >> /home/suleyman/my_server_project/.env
          echo "GONDEREN_SIFRE=${{ secrets.GONDEREN_SIFRE }}" >> /home/suleyman/my_server_project/.env

      - name: Python Servisini Yeniden Baslat
        run: sudo systemctl restart gelivyai.service
