name: GelivyAI Server Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Kodu GitHub-dan cek
        uses: actions/checkout@v4

      - name: Kitabxanalari yenile
        run: |
          source /home/suleyman/my_server_project/venv/bin/activate
          pip install -r requirements.txt

      - name: GitHub Secret-den API acari servere yaz
        # GitHub-dakı gizli açarı götürüb serverdə avtomatik .env faylına yazır
        run: |
          echo "MY_SECRET_API_KEY=${{ secrets.API_KEY }}" > /home/suleyman/my_server_project/.env
          echo "MY_SECOND_API_KEY=${{ secrets.DB }}" >> /home/suleyman/my_server_project/.env
      - name: Python Servisini Yeniden Baslat
        run: sudo systemctl restart gelivyai.service
